version: 2
jobs:
  build:
    docker:
      - image: node:9.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run: npm install -g codecov
        
      - run: npm test

      - run: codecov
